### ISSUE TITLE
naive  script 

### ISSUE THREAD

**Issue by ramy150** [KKoukiou/lxc-migration#1]
Hi, 
i follow your naive script just for testing and pass to test your solution and i have i problem in the last part of it 
checkpoint done
rsync done also
but i have an error in the last part restore failed

####################################################################
root@ubuntu:~# ./migrate2.sh u1 root@172.16.207.166
Finished checkpointing
Finished rsync
lxc-checkpoint: cgroups/cgfsng.c: create_path_for_hierarchy: 1306 Path "/sys/fs/cgroup/memory//lxc/u1" already existed.
lxc-checkpoint: cgroups/cgfsng.c: cgfsng_create: 1363 File exists - Failed to create /sys/fs/cgroup/memory//lxc/u1: File exists
lxc-checkpoint: criu.c: do_restore: 916 criu process exited 1, output:

lxc-checkpoint: criu.c: __criu_restore: 1221 restore process died
Restoring u1 failed.

######################################################################

please if you could help me it will be great 
thanks

**Comment by KKoukiou** [comment]
As I wrote you in the email this is probably compatibility with your system and CRIU. By the cgroup directory I can see you 're using systemd, whilst when I was dealing with that I was using upstart, because I was facing some issues as well when under systemd. 

Cheers
